# -*- coding: utf-8 -*-
"""Replication_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CoULoXLM36oasMndR96nFY0Thz6FS8Ze
"""

import json
import numpy as np
import pandas as pd
import argparse
import os

from tqdm import tqdm
from itertools import product
from datetime import datetime
from multiprocessing import Pool

"""## Load Data"""

ratings_df = pd.read_csv("ml-1m/ratings.dat",
                      delimiter="::",
                      names=["userId", "movieId", "rating", "tstamp"],
                      engine='python')

# data = Dataset.load_builtin('ml-1m')

# ratings_df = pd.DataFrame(data.raw_ratings, columns=["userId", "movieId", "rating", "tstamp"])
rating_matrix = ratings_df.pivot(index='userId', columns='movieId', values='rating')
rating_matrix

"""## Relevance Calculation

Relevance: Essentialy scales user rating on a 0 to 1 scale with a 0 meaning item is irrelevant to user and 1 meaning the item is very relevant
"""

# Calculate relevance matrix

# In group recommendations, we first compute relevance of candidate items to users
# This produces a full user-item interaction matrix where each entry represents pairwise relevance
# This is typically computed as r_ui / r_max, or a user-item rating divided by the maximum possible rating
r_max = 5.0
r_min = 0.5
rel_min = r_min / r_max
rel_max = 1.0

# calculates relevance for single user-item pair interaction
def get_relevance(rating):
  if np.isnan(rating): return 0.0
  rel = rating / r_max
  return max(rel_min, min(rel_max, rel)) # Clamps value between rel_min and rel_max

relevance_matrix = rating_matrix.map(get_relevance)

"""## Calculations

### Utility Calculations

Ulility: Measures how satisfied a user is with a list of items

Proportional Utility: Meausres how satisfied a user is with a list of items relative to their own top-k list
"""

# Utility calculations, under definition 3.1

# Average utility
def utility_a(user: str, recommendations: list[str]) -> int:
  list_size = len(recommendations) # K, in the paper
  rel_sum = int(relevance_matrix.loc[user, recommendations].sum())
  utility = rel_sum / (list_size * rel_max)
  return utility

# Proportionality utility
def utility_p(user: str, recommendations: list[str]) -> int:
  list_size = len(recommendations) # K, in the paper

  rel_sum = relevance_matrix.loc[user, recommendations].sum()

  # Get the user's top list_size favorite items
  user_ratings = rating_matrix.loc[user].sort_values(ascending=False)
  top_items = user_ratings.index[:list_size]

  denominator = relevance_matrix.loc[user, top_items].loc[top_items.isin(recommendations)].sum()
  if denominator == 0: return 0.0 # Handle zero denominator to avoid division by zero

  utility = rel_sum / denominator
  return utility

"""### Social Welfare Calculation"""

# Social welfare describes the aggregation of individual utilities within a group
# AKA the average satisfaction with recommended list within a group
# Via the paper, this is stated under Definition 3.2

def social_welfare(group, recommendations, utility_function):
  group_size = len(group)
  welfare_sum = 0.0
  for user in group:
    welfare_sum += utility_function(user, recommendations)
  return welfare_sum / group_size

"""### Fairness"""

# Fairness depicts how imbalanced user satisfaction is
# Via the paper, this is stated under Definition 3.3

# Least Misery: Worst case user satisfaction
def fairness_lm(group: list[str], recommendations: list[str], utility_function):
  utilities = [utility_function(user, recommendations) for user in group]
  return min(utilities)

# Variance: How uneven the utilities are across group members
def fairness_var(group: list[str], recommendations: list[str], utility_function):
  utilities = [utility_function(user, recommendations) for user in group]
  variance = np.var(utilities)
  return 1 - variance

# Jain's: Are users getting a fairshare of satisfaction
def fairness_j(group: list[str], recommendations: list[str], utility_function):
  utilities = [utility_function(user, recommendations) for user in group]

  numerator = np.sum(utilities)**2
  denominator = len(utilities) * np.sum([u**2 for u in utilities])

  if denominator == 0: return 0.0 # Handle zero denominator to avoid division by zero

  fairness = numerator / denominator
  return fairness

# Min-Max Ratio: ratio between most and least satisfied user
def fairness_m(group: list[str], recommendations: list[str], utility_function):
  utilities = [utility_function(user, recommendations) for user in group]

  # Min-Max Ratio calculation
  min_utility = min(utilities)
  max_utility = max(utilities)

  if max_utility == 0: return 0.0 # Handle zero denominator to avoid division by zero

  fairness = min_utility / max_utility
  return fairness

"""## Algorithms"""

# The primary algorithms for outputting recommendation lists

# The Greedy algorithm
def greedy_algorithm(group: list[str], items: list[str], list_length: int, fairness_function, utility_function, lam: float):
  recommendations = []
  iteration = 0
  while len(recommendations) < list_length:
    iteration += 1

    best_item = None
    best_score = -1  # Initialize with a low score

    for item in items:
      if item not in recommendations:  # Avoid adding the same item multiple times
        candidate_recommendations = recommendations + [item]

        # Calculate social welfare and fairness for candidate recommendations
        sw = social_welfare(group, candidate_recommendations, utility_function)
        fairness = fairness_function(group, candidate_recommendations, utility_function)

        # Calculate combined score
        score = lam * sw + (1 - lam) * fairness

        # Update best_item and best_score if current item has a higher score
        if score > best_score:
          best_score = score
          best_item = item

    if best_item is not None:
      recommendations.append(best_item)
    else:
      break  # Break if no suitable item is found

  return recommendations

"""## Evaluation Metrics"""

import math

def evaluate(group, recommendations, test_matrix, k=10):
  precision_scores = []
  recall_scores = []
  f_scores = []
  ndcg_scores = []


  for user in group:

    if user not in test_matrix.index:
      print(f"User {user} not found in test_matrix.")
      continue
    #need to get true items from user's in the test set
    true_items = set(test_matrix.loc[user].dropna().index)

    #if user has no test data skip user
    if not true_items:
      print(f"User {user} has no test items.")
      continue

    recommended_items = recommendations[:k]
    hits = [1 if item in true_items else 0 for item in recommended_items]


    precision = sum(hits)/k
    recall = sum(hits)/ min(k, len(true_items))
    if precision + recall == 0:
        f1 = 0
    else:
        f1 = 2 * precision * recall / (precision + recall)


    dcg = sum([hit / math.log2(i + 2) for i, hit in enumerate(hits)])
    idcg = sum([1 / math.log2(i + 2) for i in range(min(len(true_items), k))])
    ndcg = dcg / idcg if idcg > 0 else 0

    precision_scores.append(precision)
    recall_scores.append(recall)
    f_scores.append(f1)
    ndcg_scores.append(ndcg)

  return {
      'precision': np.mean(precision_scores),
      'recall': np.mean(recall_scores),
      'f1': np.mean(f_scores),
      'ndcg': np.mean(ndcg_scores)
  }

"""## Execution"""


def get_recs(args):
    group, algorithm, items, list_size, fairness_function, utility_function, lam = args #unpack args
    recommendations = algorithm(group, items, list_size, fairness_function, utility_function, lam)
    group.sort(key=lambda x: int(x))
    group_id = ",".join(map(str, group))
    return (group_id, recommendations)

def create_recommendations_file(parameter_permutations):
  for  search_algorithm, list_size, utility_name, fairness_name, lam, group_file in parameter_permutations:
    # Iterate over folds for the given group_file

    fold_index = 1
    while True:
      # Deconstruct group_file to separate the fold number
      # group_file_base = f"{group_file}_fold_{fold_index}"
      group_file_name, _ = group_file.rsplit("_fold_", 1)

      group_file_path = os.path.join("groups", f"{group_file_name}_fold_{fold_index}.json")
      if not os.path.exists(group_file_path):
        break  # Stop if no more folds exist for this group_file


      # Load groups for the current fold
      with open(group_file_path, 'r') as file:
        groups = json.load(file)

      utility_function = utility_functions[utility_name]
      fairness_function = fairness_functions[fairness_name]
      algorithm = search_algorithms[search_algorithm]

      experiment_name = f"{group_file_name}_fold_{fold_index}_list-size-{list_size}_{utility_name}_{fairness_name}_{lam}_{search_algorithm}"

      output_files = os.listdir("output")
      if any(file.startswith(experiment_name) for file in output_files):
        print(f"Skipping {experiment_name} as results already exist.")
        fold_index += 1
        continue # Skip if results already exist


      
      print(f"Executing {search_algorithm} search algorithm utilizing {utility_name} utility function, {fairness_name} fairness function, list size of {list_size} and a lambda value of {lam} on group file {group_file}")

      # Parallelize group processing using multiprocessing
      with Pool() as pool:
        # Prepare arguments for get_recs_wrapper
        args = [
            (group, algorithm, items, list_size, fairness_function, utility_function, lam)
            for group in groups
        ]
        
        # Use get_recs_wrapper with pool.imap
        recs = list(tqdm(pool.imap(get_recs, args), total=len(groups)))

      all_recommendations = dict(recs)
      # Add timestamp to the filename
      timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
      filename = f'output/{experiment_name}_recommendations_{timestamp}.json'

      with open(filename, 'w') as file:
        json.dump(all_recommendations, file)

      print("Algorithm completed, results in /output")
      fold_index += 1


# This function will test all parameter_permutations and return a dictionary of paramters to average metric performance
def run_experiment(parameter_permutations, test_matrix):
  all_results = {}
  for group_file, list_size, utility_name, fairness_name, lam, search_algorithm in parameter_permutations:
    groups = all_group_files[group_file]
    utility_function = utility_functions[utility_name]
    fairness_function = fairness_functions[fairness_name]
    algorithm = search_algorithms[search_algorithm]

    experiment_name = f"{group_file}_{list_size}_{utility_name}_{fairness_name}_{lam}_{search_algorithm}"
    
    # Check if output file already exists
    output_files = os.listdir("output")
    if any(file.startswith(experiment_name) for file in output_files):
      print(f"Skipping {experiment_name} as results already exist.")
      continue

    print(f"Executing {search_algorithm} search algorithm utilizing {utility_name} utility function, {fairness_name} fairness function, list size of {list_size} and a lambda value of {lam} on group type {group_file}")

    # Parallelize group processing using multiprocessing
    with Pool() as pool:
      # Prepare arguments for get_recs_wrapper
      args = [
          (group, algorithm, items, list_size, fairness_function, utility_function, lam)
          for group in groups
      ]
      
      # Use get_recs_wrapper with pool.imap
      recs = list(tqdm(pool.imap(get_recs, args), total=len(groups)))

    all_recommendations = dict(recs)
    # Add timestamp to the filename
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f'output/{experiment_name}_recommendations_{timestamp}.json'

    with open(filename, 'w') as file:
      json.dump(all_recommendations, file)

    print("Algorithm completed, results below")
    print(results_df)
    # Evaluate the recommendations
    results_groups = []
    for group_id, recommendations in all_recommendations.items():
      group = list(map(int, group_id.split(",")))
      result = evaluate(group=group, recommendations=recommendations, test_matrix=test_matrix, k=list_size)
      results_groups.append(result)

    results_df = pd.DataFrame(results_groups).mean()

    all_results[(group_file, list_size, utility_name, fairness_name, lam, search_algorithm)] = results_df
  return all_results

if __name__ == "__main__":
  # Load groups from the groups directory
  groups_directory = "groups"
  all_group_files = {}

  for filename in os.listdir(groups_directory):
    if filename.endswith(".json"):
      group_path = os.path.join(groups_directory, filename)
      with open(group_path, 'r') as file:
          group_data = json.load(file)
      
      # Use the filename (without extension) as the group key
      group_key = os.path.splitext(filename)[0]
      
      all_group_files[group_key] = group_data

  items = rating_matrix.columns.tolist()
  # Parameters
  fairness_functions = {'var': fairness_var}
  utility_functions = {'a': utility_a, 'p': utility_p}
  # fairness_functions = {'lm': fairness_lm, 'var': fairness_var, 'j': fairness_j, 'm': fairness_m}
  list_sizes = [3, 5, 10]
  lambdas = [0.5, 0.7, 0.9]
  search_algorithms = {'greedy': greedy_algorithm}

  # Determine permutations to be calculated
  # The order defines the order of the parameters in the output file
  parameter_permutations = list(product(search_algorithms, list_sizes, utility_functions.keys(), fairness_functions.keys(), lambdas, all_group_files.keys()))
  filtered_permutations = []
  output_files = os.listdir("output")
  for params in parameter_permutations:
    search_algorithm, list_size, utility_name, fairness_name, lam, group_file = params
    experiment_name = f"{group_file}_list-size-{list_size}_{utility_name}_{fairness_name}_{lam}_{search_algorithm}"

    # Check if any file starts with the experiment name
    if not any(file.startswith(experiment_name) for file in output_files):
      filtered_permutations.append(params)
    else:
      print(f"Skipping {experiment_name} as results already exist.")

  # Parse command-line arguments
  parser = argparse.ArgumentParser(description="Run recommendation experiments with parameter splits.")
  parser.add_argument("num_splits", type=int, nargs="?", default=1, help="Number of splits to divide parameter_permutations into (default: 1).")
  parser.add_argument("split_number", type=int, nargs="?", default=0, help="The split number to execute (0-indexed, default: 0).")
  args = parser.parse_args()

  num_splits = args.num_splits
  split_number = args.split_number

  # Validate split_number
  if split_number < 0 or split_number >= num_splits:
      raise ValueError("split_number must be between 0 and num_splits - 1.")

  # Split parameter_permutations
  split_size = len(filtered_permutations) // num_splits
  start_index = split_number * split_size
  end_index = start_index + split_size if split_number < num_splits - 1 else len(filtered_permutations)
  parameter_permutations_split = filtered_permutations[start_index:end_index]

  # Execute only the specified split
  # results = run_experiment(parameter_permutations_split, rating_matrix)
  create_recommendations_file(parameter_permutations_split)